---

- hosts: '*'
  vars:
  remote_user: solidfire
  become: true

  tasks:

  - name: Role Facts
    set_fact:
      block_device: '/dev/sdb'

  - name: Run iptables for Heketi
    script: gluster-iptables.sh

  - name: Install Kernel Modules
    modprobe:
      name: "{{ item }}"
      state: present
    with_items:
      - dm_snapshot
      - dm_mirror
      - dm_thin_pool

  - name: Install Packages
    apt:
      name: "{{ item }}"
    with_items:
      - glusterfs-client

  - name: Add Apt Repo
    shell: |
      add-apt-repository ppa:gluster/glusterfs-3.12
      apt-get update
      apt-get install -y glusterfs-client
