---
# Run on K8s master

- hosts: 'k8s0'
  vars:
    heketi_server: 'http://localhost:'
    heketi_github_version: 'v6.0.0'
    heketi_docker_version: '5'
    gluster_version: 'gluster3u13_centos7'
    dir_target: "{{ ansible_env.HOME }}/heketi"
    dir_heketi: "{{ dir_target }}/extras/kubernetes"
    storage_nodes: 'k8s0 k8s1 k8s2'
    num_nodes: 3
  remote_user: solidfire
  become: true

  tasks:

  # Check for existenz of raw storage devices

  - name: Clone Heketi repo
    git:
      repo: 'https://github.com/heketi/heketi.git'
      dest: "{{ dir_target }}"
      version: "{{ heketi_github_version }}"

  - name: Modify heketi-bootstrap image value
    lineinfile:
      dest: "{{ ansible_env.HOME }}/heketi/extras/kubernetes/heketi-bootstrap.json"
      state: present
      regexp: '^                "image": "heketi/heketi:dev",'
      line:    "                \"image\": \"heketi/heketi:{{ heketi_docker_version }}\","

  - name: Modify heketi-deployment image value
    lineinfile:
      dest: "{{ ansible_env.HOME }}/heketi/extras/kubernetes/heketi-deployment.json"
      state: present
      regexp: '^                "image": "heketi/heketi:dev",'
      line:    "                \"image\": \"heketi/heketi:{{ heketi_docker_version }}\","

  - name: Modify glusterfs-daemonset image value
    lineinfile:
      dest: "{{ ansible_env.HOME }}/heketi/extras/kubernetes/glusterfs-daemonset.json"
      state: present
      regexp: '^                        "image": "gluster/gluster-centos:latest",'
      line:    "                        \"image\": \"gluster/gluster-centos:{{ gluster_version }}\","

  - name: Get and extract Heketi Client
    unarchive:
      src: https://github.com/heketi/heketi/releases/download/{{ heketi_github_version }}/heketi-client-{{ heketi_github_version }}.linux.amd64.tar.gz
      dest: "{{ ansible_env.HOME }}"
      remote_src: yes
      creates: "{{ ansible_env.HOME }}/heketi-client"

  - name: Check for GlusterFS DaemonSets
    shell: 'kubectl get ds glusterfs --no-headers=1'
    register: check_glusterfs_ds
    ignore_errors: true

  - name: Create K8s Daemonset for GlusterFS
    shell: kubectl create -f "{{ dir_heketi }}/glusterfs-daemonset.json"
    when: check_glusterfs_ds.rc != 0

  - name: Label K8s Nodes
    #shell: kubectl label `kubectl get no -o name | cut -d/ -f2 | perl -pe 's/$/ /'| perl -pe chomp` storagenode=glusterfs
    shell: "kubectl label node {{ storage_nodes }} storagenode=glusterfs"
    ignore_errors: true

  - name: Pods wait for
    shell: "kubectl get po -n default | grep glusterfs- |grep Running |wc -l"
    register: glusterfs_daemonset_ready
    retries: 24 
    delay: 5 
    until: glusterfs_daemonset_ready.stdout == "{{ num_nodes }}"

  #- debug: msg="{{ glusterfs_daemonset_ready.stdout }}"

  - name: Create K8s Service Account
    shell: kubectl create -f "{{ dir_heketi }}/heketi-service-account.json"
    ignore_errors: true

  - name: Create K8s Cluster Role Binding
    shell: kubectl create clusterrolebinding heketi-gluster-admin --clusterrole=edit --serviceaccount=default:heketi-service-account
    ignore_errors: true

  - name: Create K8s Secret
    shell: kubectl create secret generic heketi-config-secret --from-file="{{ dir_heketi }}/heketi.json"
    ignore_errors: true

  - name: Check for Heketi Bootstrap
    shell: kubectl get deployment deploy-heketi --no-headers=1
    register: check_heketi_bootstrap
    ignore_errors: true

  - name: Create Heketi Bootstrap
    shell: kubectl create -f "{{ dir_heketi }}/heketi-bootstrap.json"
    when: check_heketi_bootstrap.rc != 0

  - name: Wait for Heketi Bootstrap
    shell: "kubectl get po | grep '^deploy-heketi-' | grep ' Running '"
    register: wait_for_heketi_bootstrap
    retries: 24 
    delay: 5
    until: wait_for_heketi_bootstrap.rc== 0

  - name: Copy custom topology
    copy:
      src: "topology.json"
      dest: "{{ dir_heketi }}"
      mode: 0644

  #- name: Get Heketi server ip and port
  #  shell: |
  #    kubectl get svc deploy-heketi --no-headers -o=custom-columns=IP:.spec.clusterIP,PORT:.spec.ports[*].targetPort| perl -pe 's/(\S+)\s+(\S+)/$1:$2/'
  #  register: heketi_ip_port

  - name: Get Heketi server ip
    shell: |
      kubectl get svc deploy-heketi --no-headers -o=custom-columns=IP:.spec.clusterIP,PORT:.spec.ports[*].targetPort| perl -pe 's/(\S+)\s+\S+/$1/'
    register: heketi_ip

  - name: Get Heketi server ip and port
    shell: |
      kubectl get svc deploy-heketi --no-headers -o=custom-columns=IP:.spec.clusterIP,PORT:.spec.ports[*].targetPort| perl -pe 's/\S+\s+(\S+)/$1/'
    register: heketi_port

  - debug: msg="{{ heketi_ip.stdout }}:{{ heketi_port.stdout }}"

  - name: Wait 300 seconds for port 8080 of any IP to become open on the host, don't start checking for 10 seconds
    wait_for:
      host: "{{ heketi_ip.stdout }}"
      port: "{{ heketi_port.stdout }}"
      delay: 10

  - name: Load Heketi topology
    shell: "{{ ansible_env.HOME }}/heketi-client/bin/heketi-cli -s http://{{ heketi_ip.stdout }}:{{ heketi_port.stdout }} topology load --json={{ dir_heketi }}/topology.json"

  - name: Setup Openshift Heketi storage
    shell: "{{ ansible_env.HOME }}/heketi-client/bin/heketi-cli -s http://{{ heketi_ip.stdout }}:{{ heketi_port.stdout }} setup-openshift-heketi-storage"
    ignore_errors: true

  - name: Create Heketi storage
    shell: kubectl create -f heketi-storage.json
    ignore_errors: true

  - name: Delete Bootstrap Heketi
    shell: kubectl delete all,service,jobs,deployment,secret --selector="deploy-heketi"

  - name: Create Permanent Heketi
    shell: kubectl create -f "{{ dir_heketi }}/heketi-deployment.json"
