---
# Ansible for installing GlusterFS requirements on K8s cluster machines.

- hosts: '*'
  vars:
    gluster_repo: 'ppa:gluster/glusterfs-3.12'
  remote_user: solidfire
  become: true

  tasks:

  #- name: Role Facts
  #  set_fact:
  #    block_device: '/dev/sdb'

  - name: Run iptables for Heketi
    script: gluster-iptables.sh

  - name: Install Kernel Modules
    modprobe:
      name: "{{ item }}"
      state: present
    with_items:
      - dm_snapshot
      - dm_mirror
      - dm_thin_pool

  - name: Add Apt Repo
    shell: |
      add-apt-repository "{{ gluster_repo }}"
      apt-get update

  - name: Install Packages
    apt: 
      name: glusterfs-client
