---

- hosts: 'kube-master'
  vars:
    user: solidfire
  #remote_user: root
  become: true

  tasks:

  - name: Add Kubernetes shell goodness
    blockinfile:
      path: ~/.bashrc
      insertafter: EOF
      block: |
        # Alias for kubectl and command line completion
        # Requires: bash-completion
        alias kctl=kubectl
        source <(kubectl completion bash  | sed s/kubectl/kctl/g)

