---
# Ansible 

- hosts: '127.0.0.1'
  vars:
    inv_file: '~/.kubespray/inventory/inventory.cfg'
  run_once: true
  connection: local

  tasks:

  - name: Read Kubespray inventory "{{ inv_file }}"
    command: "cat {{ inv_file }}"
    register: result

  - name: List Kubespray inventory "{{ inv_file }}""
    debug: msg="{{ result.stdout_lines }}" 
