---

- hosts: '127.0.0.1'
  vars:
    kscli_src: '.kubespray.yml'
    dir_dest: '~'
  connection: local

  tasks:

  - name: Copy kubespray-cli config file
    copy:
      src:  "{{ kscli_src }}"
      dest: "{{ dir_dest }}"
      mode: 0644
      force: no

