---

- hosts: '127.0.0.1'
  vars:
    kscli_src: '.kubespray.yml'
    dir_dest: '~'
    dir_kube: '~/.kubespray'
    inv_dir:  '~/.kubespray/inventory'
    inv_src:  'inventory.cfg'
    inv_dest: "{{ inv_dir }}/inventory.cfg"
    group_dir:  "{{ inv_dir }}/group_vars"
    all_src:  'all.yml'
    all_dest: "{{ group_dir }}/all.yml"
    k8s_cluster_src:  'k8s-cluster.yml'
    k8s_cluster_dest: "{{ group_dir }}/k8s-cluster.yml"
    nodes:   '127.0.0.1'
    etcds:   '127.0.0.1'
    masters: '127.0.0.1'
  connection: local

  tasks:

  - name: Copy kubespray-cli config file
    # This address kubespray requirement (bug?)
    copy:
      src:  "{{ kscli_src }}"
      dest: "{{ dir_dest }}"
      mode: 0644
      force: no

