---

- hosts: '*'
  vars:
    user: solidfire
  gather_facts: false
  become: true

- import_playbook: gluster-heketi-pre.yml
- import_playbook: gluster-heketi.yml block_device='/dev/sdd'
- import_playbook: gluster-storage-class.yml

