---

- hosts: '*'
  vars:
  #remote_user: root
  gather_facts: False

  tasks:

  - name: Allow Passwordless Sudo for solidfire
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^solidfire'
      line: 'solidfire ALL=(ALL) NOPASSWD: ALL'
      insertafter: '^%sudo	ALL=(ALL:ALL) ALL'
      validate: 'visudo -cf %s'
    become: true

  - name: Set authorized key took from file
    authorized_key:
      user: solidfire
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  - name: Turn off pager for systemctl
    lineinfile:
      dest: ~/.bashrc
      state: present
      regexp: '^export SYSTEMD_PAGER='
      line: 'export SYSTEMD_PAGER=""'
