---

- hosts: '*'
  vars:
    #nfs_server: 10.117.31.165
    #nfs_export_dir: '/export'
    #nfs_client_dir: '/local'
  #remote_user: root
  become: true

  tasks:

  #- name: Disable Service Apparmor
  #  service:
  #    name: apparmor
  #    enabled: no
  #    state: stopped
  #  ignore_errors: true

  #- name: Remove apparmor package
  #  apt:
  #    name: apparmor
  #    state: absent

  - name: Allow IPv4 Forwarding
    shell: sysctl -w net.ipv4.ip_forward=1

  - name: Disable Swap
    shell: /sbin/swapoff -a
    register: result

  - name: Edit Fstab
    lineinfile:
      path: /etc/fstab
      state: absent
      regexp: '^/dev/mapper/main-swap '

  - name: Install Packages
    apt:
      name: "{{ item }}"
    with_items:
      - thin-provisioning-tools
      - lvm2
      - dnsutils
      - net-tools
      - fortune-mod
      - cowsay
      - tree
      #- nfs-common
      #- container-storage-setup

  - name: Configure Login Banner
    script: fortune_cowsy.sh

  - name: Copy MOTD
    copy:
      src: motd-solidfire.txt
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644

  #- name: Create dir local
  #  file:
  #    path: "{{ nfs_client_dir }}"
  #    state: directory
  #    mode: 0777

  #- name: Mount NFS dir
  #  mount:
  #    path: "{{ nfs_client_dir }}"
  #    state: mounted
  #    src: "{{ nfs_server }}:{{ nfs_export_dir }}"
  #    fstype: nfs
  #    opts: 'auto,nofail,noatime,nolock,intr,tcp,actimeo=1800'
