---
# Ansible for OpenEBS
# Requires disk to already be formatted and mounted

- hosts: '127.0.0.1'
  vars:
    namespace:            'openebs'
    deploy:               'openebs-apiserver'
    chart:                'stable/openebs'
    helm_name:            'openebs'
    block_device_openebs: '/dev/sdd'
  connection: local

  tasks:

  - name: Check for OpenEBS DaemonSets
    shell: "kubectl get deployment {{ deploy }} -n {{ namespace }} --no-headers=1"
    register: check_openebs
    ignore_errors: true

  - name: Add Helm default repo
    shell: "helm repo add stable https://kubernetes-charts.storage.googleapis.com/"
    when: check_openebs.rc != 0

  - name: Install OpenEBS with Helm package manager
    shell: "helm install --namespace {{ namespace }} {{ helm_name }} {{ chart }}"
    when: check_openebs.rc != 0

  - name: Check for OpenEBS DaemonSets
    shell: "kubectl get deployment {{ deploy }} -n {{ namespace }} --no-headers=1"
    register: check_openebs_apiserver
    retries: 36
    delay: 1
    until: check_openebs_apiserver.rc == 0

  - name: Set default storage class
    shell: "kubectl patch storageclass openebs-jiva-default -p '{\"metadata\": {\"annotations\":{\"storageclass.kubernetes.io/is-default-class\":\"true\"}}}'"
    when: check_openebs_apiserver.rc == 0
