apiVersion: v1
kind: ConfigMap
metadata:
  namespace: load-balance
  name: metallb-config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.117.67.252-10.117.67.252
