apiVersion: v1
kind: ConfigMap
metadata:
  namespace: load-balance
  name: metallb-config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.7.1-192.168.7.255
