---
# Ansible for deploying Nginx-ingress

#- hosts: 'kube-master'
- hosts: '127.0.0.1'
  vars:
      dir_target: '{{ ansible_env.HOME }}'
      namespace: 'ingress'
      helm_name: 'nginx-ingress'
      chart: 'stable/nginx-ingress'
      deploy: 'nginx-ingress-controller'
  remote_user: solidfire
  #become: true
  run_once: true
  environment:

  tasks:

  #- name: Role Facts
  #  set_fact:
  #    block_device: '/dev/sdb'

  - name: Check for Nginx-ingress deployment
    shell: "kubectl get deployment {{ deploy }} -n {{ namespace }} --no-headers=1"
    register: check_nginx_ingress
    ignore_errors: true

  - name: Install Nginx-ingress helm chart
    command: "helm install {{ chart }} -n {{ helm_name }} --namespace {{ namespace }}"
    when: check_nginx_ingress.rc != 0
    register: install_chart

  - debug: var=install_chart.stdout_lines

  - name: Check for Nginx-ingress deployment
    shell: "kubectl get deployment {{ deploy }} -n {{ namespace }} --no-headers=1"
    register: check_nginx_ingress_controller
    retries: 36
    delay: 1
    until: check_nginx_ingress_controller.rc == 0
